### ISSUE TITLE
关闭wifi死机重启

### ISSUE THREAD

**Issue by cnsilvan** [liminghuang/asrock_deskmini310_hackintosh#10]
在bios中开启 虚拟化后有这个问题。
主要是不开启虚拟化 无法使用docker
但是已经稳定运行好久好久了 其他貌似看起来没什么问题。

**Comment by cnsilvan** [comment]
偶尔关闭又没有死机了。。。黑苹果果然不稳定。。。

**Comment by xiaooloong** [comment]
bcm94352z 这个卡我在 p650se 笔记本、dell latitude 3490 笔记本、台式机 z390 和 h310 主板上都使用过，都没有发生你这种情况。

下次安装的时候用纯净版系统试试吧，如果还是偶尔出现问题，换个白果拆机卡试试。
