### ISSUE TITLE
没有加入传感器

### ISSUE THREAD

**Issue by cnsilvan** [liminghuang/asrock_deskmini310_hackintosh#12]
没有传感器，无法检测温度

**Comment by liminghuang** [comment]
<img width="329" alt="螢幕快照 2019-07-06 下午1 07 41" src="https://user-images.githubusercontent.com/1393762/60751828-103dda80-9fef-11e9-9b8a-18e787981fda.png">
很正常

**Comment by cnsilvan** [comment]
> <img alt="螢幕快照 2019-07-06 下午1 07 41" width="329" src="https://user-images.githubusercontent.com/1393762/60751828-103dda80-9fef-11e9-9b8a-18e787981fda.png">
> 
> 很正常

好奇怪，我用你的efi就没有这些，然后安装了几个kext才有的

**Comment by liminghuang** [comment]
@cnsilvan 因為不是每個人都需要看這些資訊，多放一些用不到kext只是增加系統負擔。

**Comment by cnsilvan** [comment]
> @cnsilvan 因為不是每個人都需要看這些資訊，多放一些用不到kext只是增加系統負擔。

好的 谢谢你的回答

**Comment by Mari2019** [comment]
@Silvan，那么究竟要安装哪些kext，才能得到你这些传感器信息呢？




------------------ 原始邮件 ------------------
发件人: "Silvan"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 中午12:11
收件人: "liminghuang/asrock_deskmini310_hackintosh"<asrock_deskmini310_hackintosh@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [liminghuang/asrock_deskmini310_hackintosh] 没有加入传感器 (#12)



  
很正常
  
好奇怪，我用你的efi就没有这些，然后安装了几个kext才有的

**Comment by xiaooloong** [comment]
@Mari2019 我直接把 FakeSMC 的一套装了。

```
FakeSMC_ACPISensors.kext
FakeSMC_CPUSensors.kext
FakeSMC_GPUSensors.kext
FakeSMC_LPCSensors.kext
FakeSMC_SMMSensors.kext
```

**Comment by Mari2019** [comment]
Loong, thanks, 有空我也去试试看。




------------------ 原始邮件 ------------------
发件人: "xiaooloong"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 下午4:43
收件人: "liminghuang/asrock_deskmini310_hackintosh"<asrock_deskmini310_hackintosh@noreply.github.com>; 
抄送: "曹屮"<1274015442@QQ.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [liminghuang/asrock_deskmini310_hackintosh] 没有加入传感器 (#12)




@Mari2019 我直接把 FakeSMC 的一套装了。
 FakeSMC_ACPISensors.kext FakeSMC_CPUSensors.kext FakeSMC_GPUSensors.kext FakeSMC_LPCSensors.kext FakeSMC_SMMSensors.kext

**Comment by Irishemma** [comment]
> @Mari2019 我直接把 FakeSMC 的一套装了。
> 
> ```
> FakeSMC_ACPISensors.kext
> FakeSMC_CPUSensors.kext
> FakeSMC_GPUSensors.kext
> FakeSMC_LPCSensors.kext
> FakeSMC_SMMSensors.kext
> ```

这些在kext updater和clover configuration里木有看到，是在网上找么？谢谢～

**Comment by xiaooloong** [comment]
> > @Mari2019 我直接把 FakeSMC 的一套装了。
> > ```
> > FakeSMC_ACPISensors.kext
> > FakeSMC_CPUSensors.kext
> > FakeSMC_GPUSensors.kext
> > FakeSMC_LPCSensors.kext
> > FakeSMC_SMMSensors.kext
> > ```
> 
> 这些在kext updater和clover configuration里木有看到，是在网上找么？谢谢～

这些和 FakeSMC/VirtualSMC 是一起的。下载解压就能得到。
