### ISSUE TITLE
4k显示器开缩放, 会卡顿

### ISSUE THREAD

**Issue by sulin2018** [liminghuang/asrock_deskmini310_hackintosh#14]
4k显示器, 缩放成2k/1080p的时候变卡

**Comment by cnsilvan** [comment]
刷新多少hz？我这边没有这个问题。

**Comment by sulin2018** [comment]
60hz 我也不知道为什么，有的缩放分辨率下卡，有的不卡 都是很清晰的分辨率

**Comment by liminghuang** [comment]
4K螢幕我是裝這套去調整，請勾選有閃電符號的螢幕參數
https://github.com/avibrazil/RDM

**Comment by sulin2018** [comment]
我也是用的这个软件 当我切换到有闪电标志的分辨率就会变卡 切换到没有闪电标志的分辨率就正常 运行速度很快 特别是当我用IntelliJ系列软件编码的时候 很卡顿

**Comment by liminghuang** [comment]
先確定你的螢幕型號支援多少刷新率，4K螢幕有時候不同接口支援不同刷新，例如我的螢幕接DP才可以60hz，接HDMI只有50。
目前為止我4K螢幕都很正常

**Comment by sulin2018** [comment]
显示器和电脑应该都没问题 不知道是不是IntelliJ IDE的问题 我自己再研究研究吧 谢谢了！

**Comment by yangyuw** [comment]
@sulin2018 是idea的问题，idea很吃显卡，换双通道内存会好点，然后idea不全屏会好些。我也是因为这个问题头疼，windows下就很流畅，mac下显卡性能太弱

**Comment by yangyuw** [comment]
@sulin2018 昨天第二条内存到了, 亲测双通道jetbrains 全家桶一点也不卡了🙅‍♀️

**Comment by sulin2018** [comment]
@yu-yang2 yes， 确实是因为内存问题，新买的内存到货了， 加上之后流畅运行了， mac好像确实需要双通道才能完全发挥性能。之前编辑的时候cpu就飙高， 我还以为是cpu问题。
