### ISSUE TITLE
使用ps2019死机重启

### ISSUE THREAD

**Issue by cnsilvan** [liminghuang/asrock_deskmini310_hackintosh#16]
怀疑显卡驱动问题

**Comment by liminghuang** [comment]
最近看到這新聞
https://appleinsider.com/articles/19/06/20/chrome-causing-final-cut-pro-x-to-freeze-and-crash

如果有用Chrome，建議會使用到IGPU的操作時，把chrome徹底關閉。
操作FCPX/Adobe Lightroom後，只要進入睡眠，就會無法喚醒。
還在觀察中，目前不確定這新聞真實性

**Comment by liminghuang** [comment]
@cnsilvan 可以考慮外接顯卡
請參考這個branch
https://github.com/liminghuang/asrock_deskmini310_hackintosh/tree/iMac_with_RX580

**Comment by cnsilvan** [comment]
> @cnsilvan 可以考慮外接顯卡
> 請參考這個branch
> https://github.com/liminghuang/asrock_deskmini310_hackintosh/tree/iMac_with_RX580

好的 谢谢回答
