### ISSUE TITLE
请问下 使用i7 7800es qn8h可以完美黑苹果吗？

### ISSUE THREAD

**Issue by Jimmuy** [liminghuang/asrock_deskmini310_hackintosh#19]
cpu 不显版，准备剩下的配置用和楼主一样的，手边有一个i7 es处理器 不知道能不能完美黑

**Comment by liminghuang** [comment]
沒試過
請參考官方CPU支援列表
http://asrock.com/nettop/Intel/DeskMini%20310%20Series/index.asp#CPU

**Comment by qwhuang** [comment]
没问题，我的就是8700T ES，而且我装过4台310了，同样的U，都正常。

**Comment by Jimmuy** [comment]
> ，



> 没问题，我的就是8700T ES，而且我装过4台310了，同样的U，都正常。

好的，可以告知下你的配置清单吗？还有你有试过可以使用苹果的触控板吗？谢谢啦

**Comment by huangguoji** [comment]
qn8h 可以完美黑苹果  我用的就是这个u

**Comment by wuxuguang** [comment]
qn8h用了这个版本的efi，插上hdmi输出能进到clover，但重启之后显示器一直黑屏，知道是怎么回事吗

**Comment by huangguoji** [comment]
@wuxuguang 
拔下来 重新插一下就好了   出现这种没信号 我就是这么解决的

**Comment by liminghuang** [comment]
HDMI要重插，用DP比較沒有問題，個人建議用DP

**Comment by huangguoji** [comment]
或者换用dp转hdmi线

**Comment by wuxuguang** [comment]
用的显示器是支持dp的，搬家的时候搞丢了，暂时没有dp只有hdmi

**Comment by huangguoji** [comment]
京东一根dp吧

**Comment by wuxuguang** [comment]
谢谢大佬们热心解答 @huangguoji @liminghuang 

顺便问下，bios是4.1版本，是不是不需要做任何改动直接放进efi分区就好了？

**Comment by huangguoji** [comment]
@wuxuguang  
没问题

**Comment by wuxuguang** [comment]
拔了重插似乎不行，看来只能等着买一根dp线明天试试了

**Comment by huangguoji** [comment]
@wuxuguang 
不会啊 我就是用的hdmi啊  重插是可以的

**Comment by huangguoji** [comment]
@wuxuguang 
我的还是 hdmi转vga

**Comment by wuxuguang** [comment]
我这确实不行，难道是因为我这是一台4k的显示器？

**Comment by innov8go** [comment]
@wuxuguang  hdmi/DP 4k显示器都正常

**Comment by wuxuguang** [comment]
@sjje 我看网上说这个hdmi口不是2.0的，所以不支持4k@60hz的输出，所以我装好了，连接这个显示器，也黑屏

**Comment by wuxuguang** [comment]
用这个efi装完了，不过我的网卡是BCM94360CS2，似乎用不了，需要做什么操作吗 
@huangguoji @liminghuang

**Comment by huangguoji** [comment]
@wuxuguang   
我也是这个网卡 转接的 可以用啊

**Comment by huangguoji** [comment]
@wuxuguang 
这个网卡是免驱的 不需要什么设置

**Comment by wuxuguang** [comment]
@huangguoji 是网卡和转接卡短路了，在转接卡的螺丝固定处贴上绝缘胶布就可以了。。。

**Comment by huangguoji** [comment]
@wuxuguang 
我没固定 装了nvme硬盘后 压住了

**Comment by shownb** [comment]
@wuxuguang @huangguoji 直接扔个wifi的淘宝链接来可以吗？

**Comment by ghost** [comment]
我的就是8700es，不过声卡驱动有些问题，音乐根本没发听。

**Comment by Jimmuy** [comment]
> 我的就是8700es，不过声卡驱动有些问题，音乐根本没发听。

我的可以，用了万能驱动好像就好了，deskmini
