### ISSUE TITLE
开机启动过程屏幕会灰一下。然后出现登录界面之后15秒左右系统很卡

### ISSUE THREAD

**Issue by innov8go** [liminghuang/asrock_deskmini310_hackintosh#2]

**Comment by liminghuang** [comment]
目前我使用都很正常，沒遇過這兩個問題

**Comment by easyworld** [comment]
同出现"登录界面之后15秒左右系统很卡"的问题。可以分享一下你的 /Library/Extensions 目录有哪些kext吗 @liminghuang

**Comment by liminghuang** [comment]
![image](https://user-images.githubusercontent.com/1393762/57074103-871bd600-6d15-11e9-8e2a-dc73457ca122.png)

**Comment by liminghuang** [comment]
有一些kext是後面裝其他軟體安裝進去的

**Comment by easyworld** [comment]
我用Kext updater更新最新驱动覆盖了EFI分区上的kext后可以了，开机不卡了 @sjje 你也试试看呢

**Comment by liminghuang** [comment]
只要有更新kext，一定要rebuild cache一次，最簡單方法就是用工具，例如執行一次kext updater即可

**Comment by innov8go** [comment]
@liminghuang

我是这样解决的:
安装最新的clover。 并将以下配置文件DSDT/SSDT/Config/Kext/Driver64 替换
