### ISSUE TITLE
FaceTime 麦克风没有声音

### ISSUE THREAD

**Issue by xiaooloong** [liminghuang/asrock_deskmini310_hackintosh#24]
FaceTime 通话时麦克风没有声音，对方听不到这边说话。
其他软件可以正常收音。

机箱正面版下方的耳麦二合一插孔的麦克风对应到系统里是“线路输入”，另外一个“内置麦克风”貌似没用。
![image](https://user-images.githubusercontent.com/3427147/62185642-d796e400-b395-11e9-9497-703ab34fc57c.png)
FaceTime 没有识别到这个“线路输入”，只能识别到没用的那个”内置麦克风“。应该是这个原因导致的没有声音。

而其他软件可以正常从”线路输入“使用麦克风，所以没有问题。

**Comment by xiaooloong** [comment]
轮番试了官方版本的 AppleALC 对 ALC235 的各种 layout，发现 layout 11 比 28 对音频插口的描述更准确。

不过所有的 layout，FaceTime 均无法识别麦克风设备。更换为 VoodooHDA 之后可以识别，但是视频线音频效果比较差。

**Comment by xiaooloong** [comment]
今天才发现， layout 11 下 FaceTime 可以使用耳麦二合一插孔的麦克风。

**Comment by bluehr** [comment]
哪天要是找到了如何让AppleALC 正常使用上面的3.5mic ，麻烦告诉我一下，定不胜感激，我被困扰了许久。
