### ISSUE TITLE
使用usb鼠标，不定时卡顿，只能重启

### ISSUE THREAD

**Issue by ccfredom** [liminghuang/asrock_deskmini310_hackintosh#26]
您好，使用usb鼠标的时候，会出现不定时的卡屏。鼠标移动会有明显的掉帧，非常的卡顿，只能重启才能好。

**Comment by vince-cooper** [comment]
@lfzy 作者停止维护它了。我的鼠标使用适配器最近也出现了相同问题。目前没找到好的解决办法，我准备等mac OS 10.15 Catalina出正式版后更新试下。

**Comment by liminghuang** [comment]
我沒回答代表我沒這問題，我也不知道該怎幫助你

**Comment by ccfredom** [comment]
@liminghuang  感谢您，提供的资料支持。 谢谢！  
 冒昧的问下，您是使用的触摸板嘛？

**Comment by ccfredom** [comment]
@WwhOS  这个问题，我所有的usb口都会不定时的出现问题，只能重启后才能好。有两个鼠标吧，有线和优联都会出现，目前来看是无解的？ 因为不知道确切是什么问题

**Comment by vince-cooper** [comment]
@lfzy 是的，我的情况跟你的相同，但只是最近才出现的。黑苹果太折腾了，也不稳定，最近打算放弃黑苹果，试下使用esxi安装macOS虚拟机的方式。

**Comment by innov8go** [comment]
@lfzy @WwhOS 使用蓝牙鼠标有才会卡端。无线网卡使用的苹果原装加适配板，双天线，蓝牙信号渣。  使用无线无问题。 

提供两个思路:

1. 排查系统资源繁忙引起的卡顿。
建议提供卡顿时候的更多信息。记录卡段时候，内存占用、CPU占用、GPU占用和硬盘读写速率。以及各部件温度情况。 以及使用的程序。
常见的问题:
1.CPU温度过高引起降频卡顿。
2.CPU占用过高引起的资源不足卡顿
3.单通道内存使用`jetbrains`全系列都会卡顿
4.SSD温度过高，读写速度降低
5.其他应用占满磁盘读写。引起速度降低。
等等其他。。

2.使用相同版本的bios尝试。
如果无效则尝试注入适合自己的slide值, [黑果小兵论坛](https://blog.daliansky.net/Slide-value-acquisition-and-calculation.html)

**Comment by liminghuang** [comment]
我現在用的是藍芽鍵盤logitech k760，滑鼠是logitech MX MASTER 2S

**Comment by liminghuang** [comment]
@lfzy @WwhOS 如果你藍牙會卡頓，就改用usb 無線電的滑鼠吧，另外建議用一條usb延長線，把usb接收器延長出來，不要插在主機。

**Comment by vince-cooper** [comment]
@liminghuang 谢谢你的回答。我的鼠标支持蓝牙和sb无线接收器两种连接方式，使用蓝牙连接不上，使用usb无线接收器最近出现了卡顿的现象。鼠标和usb无线接收器相距0.5m，中间也无遮挡物，所以应该不是信号的问题。

**Comment by liminghuang** [comment]
@WwhOS 你可以嘗試用延長線把接收器拉遠一點，就是不要把接收器插在主機上，因為我有朋友就是這樣做才穩定。

**Comment by vince-cooper** [comment]
@sjje 十分感谢。感觉黑苹果太折腾，也不够稳定，打算这周末尝试下esxi安装macOS虚拟机的方式。这样以后升级或恢复macOS也方便，不必重新来一遍。缺点是浪费少许性能，还可以接受。

**Comment by vince-cooper** [comment]
@liminghuang 我使用了独立供电的usb hub，usb接收器插在上面也会出现同样问题，所以感觉很是崩溃。

**Comment by vince-cooper** [comment]
@liminghuang @sjje @lfzy  给你们推荐一个工具：carbon copy cloner，可以用来复制整个磁盘系统，折腾的时候用来备份。我前阵子加了块SSD，把m.2 SSD中的系统复制到新的SSD上，再复制efi到新的SSD。这样就可以在新的SSD上直接启动系统，数据都还在。

**Comment by weimi** [comment]
我试过罗技多款鼠标都会卡顿，不管有线无线。雷蛇试过一款也卡，反而用公司便宜的dell有线鼠标毫无问题。

**Comment by AceInAndroid** [comment]
我使用trackpad2 也是卡顿 没办法 断开重连好一点

**Comment by AceInAndroid** [comment]
magic mouse2正常 trackpad2经常卡顿

**Comment by ccfredom** [comment]
已经入白  放弃折腾啦 ：）

**Comment by swanduron** [comment]
帖子挖个坟，回答一下各位的问题。我做过很长时间的测试，就我的平台来说，如果你USB系统是经过USB HUB，并且USB没有经过仔细定制的，USB HUB上驳接的所有设备都有类似的问题，尤其是USB3.0的HUB，基本是无可救药的。

**Comment by pafans** [comment]
才注意到有人提这个问题，其实解决的方法很简单，去淘宝花20块钱买一个Deskmini专用的USB 2.0扩展口，然后把鼠标和键盘的接收器插在这个扩展口就没有卡顿的问题了

**Comment by ccfredom** [comment]
最终我转了白··· 重度使用，有时候有不知名问题··

**Comment by ccfredom** [comment]
我最近 又重新装了起来，仔细排查了下。

导致鼠标严重卡顿的问题，大部分是因为固态的问题，原来用的英特尔的600p，掉速非常厉害。cpu满载的时候，不会卡顿，但是测试固态的时候，卡顿明显。换了个闪迪的固态，十分完美。

在公司内，电脑设备比较多的情况下，使用2.4G设备会有卡顿现象，但是使用有线鼠标的话。不卡顿！！ 非常完美。 

我的解决方案，供大家参考，谢谢。
