### ISSUE TITLE
Black screen with macOS Catalina 10.15

### ISSUE THREAD

**Issue by fabiocchetti** [liminghuang/asrock_deskmini310_hackintosh#27]
Hello @liminghuang,

Thank you for sharing your configuration with us.

I have an ASRock DeskMini 310 like yours, with an Intel Core i5 9500 (Intel UHD 630) as CPU.

I'm trying to perform a clean install of macOS Catalina on a 2.5" SSD, but at a certain point of the installation the screen turns black and nothing is shown. The PC does not restart and the kernel does not seem to panic, but I am unable to proceed with the installation since there's nothing on my monitor.

I thought it was something related to Intel UHD 630, so I tried to:
- Add __-disablegfxfirmware__ parameter in the boot section of config.plist file
- Update Whatevergreen kext to the last version
- Use every possible (Intel) kext injection option from Clover
- Use another video output (VGA instead of HDMI)
but nothing worked.

Do you have any suggestion? Did you notice something similar for your installation?

Thank you very much.
Have a nice day!

**Comment by liminghuang** [comment]
@fabiocchetti 
I had clean install of macOS Catalina from beta version many times, I never have the situation likes yours, especially, it's clean install. Here are many friends in the world use the EFI, I think no one has the same issue like yours. Let's clear somethings step by step.
1. Which Catalina version you install? As I know, 10.15.1 has released yesterday, I'm not sure what version you installed? 10.15.1 update some graphic drivers, you need to use dev version of Whatevergreen or event don't use it. If you use 10.15, no problem about it.
2. Clean install has to two times reboot, what step you have back screen?
3. Display port is recommended.
4. You can check the HDD light at the front of 310. The screen is black but the HDD light is flashing, maybe wait more minutes.
good luck!

**Comment by fabiocchetti** [comment]
Dear @liminghuang, thank you for your reply.

Let me answer you point-by-point with more details.

1) I'm installing the 10.15.1 version, but as explained in my previous message I updated some kexts before starting the installer.
2) I'm having the black screen before the installation step, right after the log. When I run the installer from Clover in verbose mode, I don't see any error in the log and everything appears to go smoothly (black screen with white text), but when the first installer screen should appear, the screen turns black instead. Basically I am unable to see the step with "Install macOS" or "Restore from Time Machine" options, I don't know if I've been clear.
3) Unfortunately I don't have any DisplayPort cable or adapter, moreover my monitor supports HDMI / VGA only. I tried with other monitors and cables too, without success.
4) The HDD orange light is not flashing, but as soon as I click randomy or I type something on the keyboard, it starts blinking. So it means that something is happening. I'm sure the installation welcome screen is loaded but not shown.

I created the USB installer manually via the Terminal, then I installed [this version](https://www.tonymacx86.com/resources/clover-uefi-boot-mode-with-emulated-nvram-v2-4k-r4961.433/) of Clover, mounted the EFI partition with Clover Configurator and replaced the whole EFI folder with yours. Then I replaced Lilu, AppleALC and WhateverGreen kexts with the most recent ones.

Moreover, I configured the BIOS as follows:
• Advanced > Chipset Configuration > VT-d: Disabled
• Advanced > Chipset Configuration > Onboard HD Audio: Enabled
• Advanced > USB Configuration > XHCI Hand-off: Enabled
• Security > Secure Boot: Disabled

Do you think I'm doing something wrong?
Thank you for your time.

**Comment by liminghuang** [comment]
@fabiocchetti 
All of procedure look like perfect, it should be no any issue. The only one thing I am doubt is display cable, you may try to use display port <-->HDMI cable for your monitor. I recommended the brand of cable is LINDY if you can buy it in your country. DP is native support in macOS, all discussions or guides about Hackintosh suggest the DP is the first choice.

**Comment by fabiocchetti** [comment]
Dear @liminghuang,
I've been able to complete the installation via HDMI cable, I needed to change the _ig-platform-id_ in config.plist to 0x59120000. After this change, everything went perfect and I installed Catalina 10.15.1.

But after the install I'm still having a couple of issues, I hope you can help me and share your thoughts.

- I'm not having the graphic acceleration, from "About this Mac..." I see just 31 MB of video RAM and the graphics performance is very poor. No transparency effects and slow animations.
- No audio via HDMI.

Please note that my configuration is exactly the same of your EFI foder here in this repo, but with AppleALC, Lilu and WhateverGreen updated to the latest versions and _ig-platform-id_ updated to 0x59120000. I have an Intel Core i5 9500 as CPU.

Do you have any suggestion?
Thank you once more.

**Comment by liminghuang** [comment]
@fabiocchetti 
Follow the guide https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/
0x59120000 is Kaby Lake, i5-9500 should be Coffee Lake series.
Here are two guides about intelframebuffer setting https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/ and https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/
I think that you are closed to the problem point, I hope the two guides could help you.

This main branch of this repository here didn't maintain for a while and I only can confirm it was working great in 10.14, maybe you can try 10.14 first.

**Comment by fabiocchetti** [comment]
Hello @liminghuang,
I've been able to make it work using a DisplayPort cable, as you suggested.

I restored your config.plist file — so **not** using the 0x59120000 id anymore — and it booted with graphics acceleration.

So, to recap, if someone else has my configuration (DeskMini 310 + Intel Core 9th Gen) and wants to install macOS 10.15.x:
- Starting from the files provided in this repo, I updated Lilu, AppleALC and WhateverGreen kexts to the latest versions and I changed the _ig-platform-id_ to 0x59120000. At this point I've been able to install macOS Catalina 10.15.1 without any issue, with an HDMI cable.
- After the installation, I replaced the config.plist file with the one in this repo and I used a DisplayPort cable instead. Otherwise Catalina will work anyway, but without any graphics acceleration and no audio through HDMI.

NOTES:
– Probably, if you have a DisplayPort cable it is ok to use the config.plist in this repo as it is from the beginning, so that you should have graphics acceleration immediately. In my case I didn't have the chance to try it because I bought a DisplayPort later, so I changed the _ig-platform-id_ only because I was using a HDMI cable at first.
– When the acceleration is working and you're able to see something on the screen via DisplayPort cable, you can use Hackintool to patch the ports and make the HDMI and VGA ports work as well. In my case I'm fine with using a DisplayPort cable, so no need to use Hackintool.

Closing this issue since it depended on my configuration only.

@liminghuang Thank you very much for sharing your configuration and for your support in the past days! I wish you all the best.
