### ISSUE TITLE
引导后黑屏

### ISSUE THREAD

**Issue by ReyesZYX99** [liminghuang/asrock_deskmini310_hackintosh#31]
你好，和你几乎一样的配置，只是显卡是rx590，网卡是dw1830，但是用clovet引导后，感觉一切都加载完了，应该即将进入安装界面时会黑屏，这是为什么

**Comment by liminghuang** [comment]
用display port接螢幕

**Comment by ReyesZYX99** [comment]
原来是因为这个！手头没有DP线，明天我拿一根来试试。请问可以通过修改什么地方让他支持hdmi输出吗？

**Comment by liminghuang** [comment]
補充說明，安裝過程接DP，安裝完後就可以HDMI

**Comment by ReyesZYX99** [comment]
好的，谢谢，明天试一下
