### ISSUE TITLE
双屏用不了

### ISSUE THREAD

**Issue by xlj44400** [liminghuang/asrock_deskmini310_hackintosh#33]
我替换efi 发现还是只能用hdmi  
dp输出没生效 不知道什么情况

**Comment by Kryuna** [comment]
Yep, I can't use DP either on my deskmini, I have an i5 8400 but I haven't tried this EFI folder yet, I'm going to do this now. Does it have something to do with updating to the latest version of MacOS Catalina I wonder?

是的，我不能在我的Deskmini上使用DP，我有一个i5 8400，但是我还没有尝试过这个EFI文件夹，我现在要这样做。 我想知道与更新到最新版本的MacOS Catalina是否有关？

**Comment by wqhyw** [comment]
> Yep, I can't use DP either on my deskmini, I have an i5 8400 but I haven't tried this EFI folder yet, I'm going to do this now. Does it have something to do with updating to the latest version of MacOS Catalina I wonder?
> 
> 是的，我不能在我的Deskmini上使用DP，我有一个i5 8400，但是我还没有尝试过这个EFI文件夹，我现在要这样做。 我想知道与更新到最新版本的MacOS Catalina是否有关？

HDMI do work. Need a little bit trick Using hackintool. [Refer](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html).

**Comment by xlj44400** [comment]
换了根dp线 dp接口可以使用了 就是双屏 会有问题 
先接的dp 启动后 再接hdmi dp屏就黑了  hdmi屏绿了

**Comment by Kryuna** [comment]
> > Yep, I can't use DP either on my deskmini, I have an i5 8400 but I haven't tried this EFI folder yet, I'm going to do this now. Does it have something to do with updating to the latest version of MacOS Catalina I wonder?
> > 是的，我不能在我的Deskmini上使用DP，我有一个i5 8400，但是我还没有尝试过这个EFI文件夹，我现在要这样做。 我想知道与更新到最新版本的MacOS Catalina是否有关？
> 
> HDMI do work. Need a little bit trick Using hackintool. [Refer](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html).

不，我正在使用hdmi，并且可以使用，但DP无法使用，我不知道如何通过hackintool进行补丁，因为每次插入HMDI时，在hackintool中都会显示为红色，因此我可以确定它是我自己的那个 当前正在查看，但是当我插入显示端口时，没有其他突出显示红色，与VGA相同，所以我不知道我正在使用其他两个端口。


nope I'm using hdmi and that works but DP doesn't, I don't know how to patch via hackintool because everytime I have HMDI plugged in it shows up as red in hackintool so i can figure out that it is the one I'm currently looking at, but when I plug in display port nothing else highlights red, same with VGA so I don't know what other two ports I'm working on.

**Comment by wqhyw** [comment]
> > > Yep, I can't use DP either on my deskmini, I have an i5 8400 but I haven't tried this EFI folder yet, I'm going to do this now. Does it have something to do with updating to the latest version of MacOS Catalina I wonder?
> > > 是的，我不能在我的Deskmini上使用DP，我有一个i5 8400，但是我还没有尝试过这个EFI文件夹，我现在要这样做。 我想知道与更新到最新版本的MacOS Catalina是否有关？
> > 
> > 
> > HDMI do work. Need a little bit trick Using hackintool. [Refer](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html).
> 
> 不，我正在使用hdmi，并且可以使用，但DP无法使用，我不知道如何通过hackintool进行补丁，因为每次插入HMDI时，在hackintool中都会显示为红色，因此我可以确定它是我自己的那个 当前正在查看，但是当我插入显示端口时，没有其他突出显示红色，与VGA相同，所以我不知道我正在使用其他两个端口。
> 
> nope I'm using hdmi and that works but DP doesn't, I don't know how to patch via hackintool because everytime I have HMDI plugged in it shows up as red in hackintool so i can figure out that it is the one I'm currently looking at, but when I plug in display port nothing else highlights red, same with VGA so I don't know what other two ports I'm working on.

It's may be the same issue. Try to map the 'connectors' and 'index' correctly. 
![image](https://user-images.githubusercontent.com/11343739/77870126-22ddfb00-7273-11ea-84f1-bbcb6945b5f2.png). All video output should be work well.

**Comment by wqhyw** [comment]
> > > Yep, I can't use DP either on my deskmini, I have an i5 8400 but I haven't tried this EFI folder yet, I'm going to do this now. Does it have something to do with updating to the latest version of MacOS Catalina I wonder?
> > > 是的，我不能在我的Deskmini上使用DP，我有一个i5 8400，但是我还没有尝试过这个EFI文件夹，我现在要这样做。 我想知道与更新到最新版本的MacOS Catalina是否有关？
> > 
> > 
> > HDMI do work. Need a little bit trick Using hackintool. [Refer](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html).
> 
> 不，我正在使用hdmi，并且可以使用，但DP无法使用，我不知道如何通过hackintool进行补丁，因为每次插入HMDI时，在hackintool中都会显示为红色，因此我可以确定它是我自己的那个 当前正在查看，但是当我插入显示端口时，没有其他突出显示红色，与VGA相同，所以我不知道我正在使用其他两个端口。
> 
> nope I'm using hdmi and that works but DP doesn't, I don't know how to patch via hackintool because everytime I have HMDI plugged in it shows up as red in hackintool so i can figure out that it is the one I'm currently looking at, but when I plug in display port nothing else highlights red, same with VGA so I don't know what other two ports I'm working on.

Here's my configuration. 
<img width="928" alt="image" src="https://user-images.githubusercontent.com/11343739/77870289-94b64480-7273-11ea-8a43-13911ded0427.png">
it works well.
<img width="304" alt="image" src="https://user-images.githubusercontent.com/11343739/77870309-a0a20680-7273-11ea-9a40-c67c8e02fb22.png">

**Comment by Kryuna** [comment]
> > > > Yep, I can't use DP either on my deskmini, I have an i5 8400 but I haven't tried this EFI folder yet, I'm going to do this now. Does it have something to do with updating to the latest version of MacOS Catalina I wonder?
> > > > 是的，我不能在我的Deskmini上使用DP，我有一个i5 8400，但是我还没有尝试过这个EFI文件夹，我现在要这样做。 我想知道与更新到最新版本的MacOS Catalina是否有关？
> > > 
> > > 
> > > HDMI do work. Need a little bit trick Using hackintool. [Refer](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html).
> > 
> > 
> > 不，我正在使用hdmi，并且可以使用，但DP无法使用，我不知道如何通过hackintool进行补丁，因为每次插入HMDI时，在hackintool中都会显示为红色，因此我可以确定它是我自己的那个 当前正在查看，但是当我插入显示端口时，没有其他突出显示红色，与VGA相同，所以我不知道我正在使用其他两个端口。
> > nope I'm using hdmi and that works but DP doesn't, I don't know how to patch via hackintool because everytime I have HMDI plugged in it shows up as red in hackintool so i can figure out that it is the one I'm currently looking at, but when I plug in display port nothing else highlights red, same with VGA so I don't know what other two ports I'm working on.
> 
> Here's my configuration.
> <img alt="image" width="928" src="https://user-images.githubusercontent.com/11343739/77870289-94b64480-7273-11ea-8a43-13911ded0427.png">
> it works well.
> <img alt="image" width="304" src="https://user-images.githubusercontent.com/11343739/77870309-a0a20680-7273-11ea-9a40-c67c8e02fb22.png">

You're using an iMac smbios that's why it's working. I don't think you can get framebuffer to work on a Mac Mini SMBIOS.

**Comment by xlj44400** [comment]
![image](https://user-images.githubusercontent.com/8731755/77883059-ed4a0980-7294-11ea-812c-bdf68af4f549.png)
![image](https://user-images.githubusercontent.com/8731755/77883145-15d20380-7295-11ea-8dbe-d5ee9d8c119f.png)

我的dp接口 是ok的，dp接口不行可能是你的dp线有问题，如果用的dp转HDMI的线可能就有问题
HDMI接口也是ok的

**Comment by wqhyw** [comment]
> > > > > Yep, I can't use DP either on my deskmini, I have an i5 8400 but I haven't tried this EFI folder yet, I'm going to do this now. Does it have something to do with updating to the latest version of MacOS Catalina I wonder?
> > > > > 是的，我不能在我的Deskmini上使用DP，我有一个i5 8400，但是我还没有尝试过这个EFI文件夹，我现在要这样做。 我想知道与更新到最新版本的MacOS Catalina是否有关？
> > > > 
> > > > 
> > > > HDMI do work. Need a little bit trick Using hackintool. [Refer](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html).
> > > 
> > > 
> > > 不，我正在使用hdmi，并且可以使用，但DP无法使用，我不知道如何通过hackintool进行补丁，因为每次插入HMDI时，在hackintool中都会显示为红色，因此我可以确定它是我自己的那个 当前正在查看，但是当我插入显示端口时，没有其他突出显示红色，与VGA相同，所以我不知道我正在使用其他两个端口。
> > > nope I'm using hdmi and that works but DP doesn't, I don't know how to patch via hackintool because everytime I have HMDI plugged in it shows up as red in hackintool so i can figure out that it is the one I'm currently looking at, but when I plug in display port nothing else highlights red, same with VGA so I don't know what other two ports I'm working on.
> > 
> > 
> > Here's my configuration.
> > <img alt="image" width="928" src="https://user-images.githubusercontent.com/11343739/77870289-94b64480-7273-11ea-8a43-13911ded0427.png">
> > it works well.
> > <img alt="image" width="304" src="https://user-images.githubusercontent.com/11343739/77870309-a0a20680-7273-11ea-9a40-c67c8e02fb22.png">
> 
> You're using an iMac smbios that's why it's working. I don't think you can get framebuffer to work on a Mac Mini SMBIOS.

Maybe. I didn't use Mac Mini SMBIOS.

**Comment by Kryuna** [comment]
> ![image](https://user-images.githubusercontent.com/8731755/77883059-ed4a0980-7294-11ea-812c-bdf68af4f549.png)
> ![image](https://user-images.githubusercontent.com/8731755/77883145-15d20380-7295-11ea-8dbe-d5ee9d8c119f.png)
> 
> 我的dp接口 是ok的，dp接口不行可能是你的dp线有问题，如果用的dp转HDMI的线可能就有问题
> HDMI接口也是ok的

Those settings don't work for me, they were switched back to default upon reboot! This "LVDS" keeps popping back up in my framebuffer settings everytime as well, I don't know why that's there. I'm using platform ID 0x3E9B0007. When I plug in display port cable nothing highlights in red, same with VGA, so I'm stuck using HDMI which I'm assuming is highlighted in red here, though I don't know why it's listing as DP.

这些设置对我不起作用，它们在重新启动后已切换回默认设置！ 每次，“ LVDS”都会不断在我的帧缓冲区设置中弹出，我不知道为什么会出现。 我正在使用平台ID 0x3E9B0007。 当我插入显示端口电缆时，与VGA相同，没有红色突出显示，所以我被HDMI所卡住了，我假设这里是红色突出显示，尽管我不知道为什么它被列为DP。

![Screen Shot 2020-03-30 at 7 21 23 AM](https://user-images.githubusercontent.com/57334458/77907271-5c087200-7257-11ea-96d2-b2f3b40c4ecc.png)

![Screen Shot 2020-03-30 at 7 20 03 AM](https://user-images.githubusercontent.com/57334458/77907282-5f036280-7257-11ea-925c-82a74c90eb34.png)

**Comment by xlj44400** [comment]
你替换efi 要刷新cache的

**Comment by Kryuna** [comment]
你什么意思？

**Comment by xlj44400** [comment]
![image](https://user-images.githubusercontent.com/8731755/78090880-f9050f80-73fd-11ea-878c-1aa8d6aaae8e.png)
我的双屏ok的 
先接dp 另一台显示器先关闭 然后接hdmi 然后打开关闭的显示器就行了
