### ISSUE TITLE
请问是不是核心显卡相同的cpu都可以使用

### ISSUE THREAD

**Issue by wintry** [liminghuang/asrock_deskmini310_hackintosh#4]
比如i5 9600k和i5 9400

**Comment by liminghuang** [comment]
這塊主板不支援9代Intel CPU，僅支援一款I5-9400
支援列表在這(http://asrock.com/nettop/Intel/DeskMini%20310%20Series/index.asp#CPU)

**Comment by liminghuang** [comment]
剛看一下比較表，用9400，不如用8700，但其實都會頂到CPU功耗牆，其實平衡搭配i5-8500即可

**Comment by wintry** [comment]
@liminghuang 感谢
