### ISSUE TITLE
您好,除了硬盘用的SM961一模一样的硬件,wifi和蓝牙无法使用.

### ISSUE THREAD

**Issue by picassochan** [liminghuang/asrock_deskmini310_hackintosh#5]
如题,有解决方法么?爬了很多帖子了.即使能找到硬件都无法正常使用...

谢谢

**Comment by liminghuang** [comment]
wifi用的kext是這兩隻
BrcmFirmwareData.kext
BrcmPatchRAM2.kext
你有確定放入到 /Library/Extensions這目錄嗎？

**Comment by picassochan** [comment]
> wifi用的kext是這兩隻
> BrcmFirmwareData.kext
> BrcmPatchRAM2.kext
> 你有確定放入到 /Library/Extensions這目錄嗎？

对，我爬了很多帖子，包括国外的论坛，各种方法都试了，硬件能够显示，wifi和蓝牙都能正常打开，但是无法找到任何可连接的设备。很奇怪。

**Comment by liminghuang** [comment]
@laughingchan 你天線有接好嗎？

**Comment by picassochan** [comment]
> @laughingchan 你天線有接好嗎？

淘宝重新买了根天线试试了只有.谢谢

**Comment by picassochan** [comment]
@liminghuang 确定是天线的问题了。多谢，怎么都没想到天线会有问题

**Comment by liminghuang** [comment]
@laughingchan 恭喜
