### ISSUE TITLE
启动时会卡在++++++++++++++一会，并且系统启动过程中会丢失视频信号一会

### ISSUE THREAD

**Issue by leonfox28** [liminghuang/asrock_deskmini310_hackintosh#7]
如标题所说，启动时会卡在++++++++++++++一会，这个问题如果安装aptiomemoryfix.efi（名字记不得了大概是这个）能解决。
其次就是启动过程中会黑屏，显示器提示无信号输入。等个3-6s会恢复正常进入登陆输密码的界面。

**Comment by liminghuang** [comment]
我測試的確這樣加快了，我加上去了，感謝

至於黑屏幾秒這問題，我也還沒找出原因，原本我懷疑是雙屏輸出造成，但我測試關閉第二屏還是會黑屏幾秒。

**Comment by leonfox28** [comment]
对了，你安装过程中重启的时候是选哪个来继续进行安装，我第一次重启时多出了一个什么preboot的选项，第二次重启的时候会再多出一个filevault preboot的选项，这个应该选哪个？多谢

**Comment by liminghuang** [comment]
都用預設那個啟動，都不用選。預設應該是"Boot macOS from Mac"
filevault好像是會加密磁碟，不建議選。

**Comment by leonfox28** [comment]
好的，非常感谢！

**Comment by cnsilvan** [comment]
借楼询问，你的usb扩展口可以正常使用吗？我这没办法用扩展口装系统，只能使用板载的usb接口

**Comment by leonfox28** [comment]
不好意思，我的机器上没有安装拓展的usb接口

**Comment by Mari2019** [comment]
cnsilvan commented May 21, 2019
借楼询问，你的usb扩展口可以正常使用吗？我这没办法用扩展口装系统，只能使用板载的usb接口

要使用侧边的USB扩展口，要额外加一个驱动USBPorts.kext

**Comment by cnsilvan** [comment]
> cnsilvan commented May 21, 2019
> 借楼询问，你的usb扩展口可以正常使用吗？我这没办法用扩展口装系统，只能使用板载的usb接口
> 
> 要使用侧边的USB扩展口，要额外加一个驱动USBPorts.kext

你好，我已经把USBPorts.kext放在了efi的kexts other文件夹下 重启后还是无法使用扩展口。是否需要更新什么操作？

**Comment by cnsilvan** [comment]
> > cnsilvan commented May 21, 2019
> > 借楼询问，你的usb扩展口可以正常使用吗？我这没办法用扩展口装系统，只能使用板载的usb接口
> > 要使用侧边的USB扩展口，要额外加一个驱动USBPorts.kext
> 
> 你好，我已经把USBPorts.kext放在了efi的kexts other文件夹下 重启后还是无法使用扩展口。是否需要更新什么操作？

使用最新的efi 已经好了
