### ISSUE TITLE
机箱面板 usb2.0 接口无法使用

### ISSUE THREAD

**Issue by xiaooloong** [liminghuang/asrock_deskmini310_hackintosh#8]
买了根 usb 面板线给机箱加上了侧面板的两个 USB2.0 接口，接在主板的 `USB_5_6` 接口上，进入 macOS 后接口不可用。
这是 Windows 下 HWiNFO 的截图，是图中 `Port6` 和 `Port7`  这两个接口。
![20190524172040](https://user-images.githubusercontent.com/3427147/58317585-a5727e80-7e48-11e9-89cb-3a8b5f3f04a4.jpg)

**Comment by xiaooloong** [comment]
将 `USBInjectAll.kext` 替换为下面这个回复中的定制驱动后，面板上两个 usb 和 正面 usb-c 接口都可以使用了。
http://bbs.pcbeta.com/forum.php?mod=redirect&goto=findpost&ptid=1799808&pid=48716684

**Comment by liminghuang** [comment]
@xiaooloong 感謝，我更新上去了
