### ISSUE TITLE
最新版本睡眠会重启 甚至开机自动重启

### ISSUE THREAD

**Issue by cnsilvan** [liminghuang/asrock_deskmini310_hackintosh#9]
但是启动几次应该有机会进入系统  使用过程中不定时重启

**Comment by cnsilvan** [comment]
今天看见更新了 就升级了kext 然后就挂了 大概率重启 卡启动在
![image](https://user-images.githubusercontent.com/15416002/58372083-2ade5780-7f4b-11e9-8cd7-b7c8b70329a7.png)
替换为之前的版本问题就不存在了 
基本定位在[这次提交之后就出现问题了](https://github.com/liminghuang/asrock_deskmini310_hackintosh/commit/27121180ab2133897ac1bb26d42297e367454eee)

**Comment by cnsilvan** [comment]
又定位一个问题 单独替换为USBPorts 后 开机或者唤醒时  无线鼠标会卡顿几秒 多次移动或者重启鼠标开关后恢复

**Comment by cnsilvan** [comment]
另外能不能帮忙看看 警告里面的  unknown cpu model 这个问题 我和你一样的8700啊

**Comment by liminghuang** [comment]
我都沒有卡頓問題，睡眠也不會重啟
你有跑過一次kext rebuild cache嗎？
有更新kext都要做一次這步驟，可以用kext utility或Kext Updater這兩個工具

**Comment by cnsilvan** [comment]
> 我都沒有卡頓問題，睡眠也不會重啟
> 你有跑過一次kext rebuild cache嗎？
> 有更新kext都要做一次這步驟，可以用kext utility或Kext Updater這兩個工具

每次都是rebuild cache过了的 卡顿现在自动好了 估计是信号干扰问题 但是死机和重启就不知道什么问题了 难道不能更新最新版的kext？

**Comment by cnsilvan** [comment]
> > 我都沒有卡頓問題，睡眠也不會重啟
> > 你有跑過一次kext rebuild cache嗎？
> > 有更新kext都要做一次這步驟，可以用kext utility或Kext Updater這兩個工具
> 
> 每次都是rebuild cache过了的 卡顿现在自动好了 估计是信号干扰问题 但是死机和重启就不知道什么问题了 难道不能更新最新版的kext？

可能和我的kexts位置有关 我是没有放入LE中 我是放在other中的 可能就是这种注入方式 导致的问题。我尝试一下放在LE中 待会儿再reply

**Comment by cnsilvan** [comment]
> > > 我都沒有卡頓問題，睡眠也不會重啟
> > > 你有跑過一次kext rebuild cache嗎？
> > > 有更新kext都要做一次這步驟，可以用kext utility或Kext Updater這兩個工具
> > 
> > 
> > 每次都是rebuild cache过了的 卡顿现在自动好了 估计是信号干扰问题 但是死机和重启就不知道什么问题了 难道不能更新最新版的kext？
> 
> 可能和我的kexts位置有关 我是没有放入LE中 我是放在other中的 可能就是这种注入方式 导致的问题。我尝试一下放在LE中 待会儿再reply

已尝试最新版本kext 放在/L/E 下 rebuild cache后 重启 就开始无限重启了 还好在重启了十几次后进入了系统 赶紧替换老版本保平安。

**Comment by cnsilvan** [comment]
> > > > 我都沒有卡頓問題，睡眠也不會重啟
> > > > 你有跑過一次kext rebuild cache嗎？
> > > > 有更新kext都要做一次這步驟，可以用kext utility或Kext Updater這兩個工具
> > > 
> > > 
> > > 每次都是rebuild cache过了的 卡顿现在自动好了 估计是信号干扰问题 但是死机和重启就不知道什么问题了 难道不能更新最新版的kext？
> > 
> > 
> > 可能和我的kexts位置有关 我是没有放入LE中 我是放在other中的 可能就是这种注入方式 导致的问题。我尝试一下放在LE中 待会儿再reply
> 
> 已尝试最新版本kext 放在/L/E 下 rebuild cache后 重启 就开始无限重启了 还好在重启了十几次后进入了系统 赶紧替换老版本保平安。

另外看见配置文件中 kexts注入选择的是yes  而不是 detect 
如果选择”Yes”，Clover会把EFI/Clover/kexts/Other目录里所有kexts都注入，这样假如在／L/E目录有相同的kexts，那么这些kexts会被加载两次，而且如果这些kexts的版本还不一样，会导致严重问题。

**Comment by liminghuang** [comment]
因為我目前系統都跑得很正常，我也手動睡眠好幾次都可以喚醒。
根據這份文件教學
https://www.tonymacx86.com/threads/guide-installing-3rd-party-kexts-el-capitan-sierra-high-sierra-mojave.268964/
裡面第四點
### 4. Why should I use /Library/Extensions over Clover Injected kexts ?
建議kext放在/Library/Extensions，不要放在Other

感謝你測試回報。

**Comment by cnsilvan** [comment]
> 因為我目前系統都跑得很正常，我也手動睡眠好幾次都可以喚醒。
> 根據這份文件教學
> https://www.tonymacx86.com/threads/guide-installing-3rd-party-kexts-el-capitan-sierra-high-sierra-mojave.268964/
> 裡面第四點
> 
> ### 4. Why should I use /Library/Extensions over Clover Injected kexts ?
> 建議kext放在/Library/Extensions，不要放在Other
> 
> 感謝你測試回報。

又发现hdmi无法使用。hdmi链接的4K显示器

**Comment by cnsilvan** [comment]
> 因為我目前系統都跑得很正常，我也手動睡眠好幾次都可以喚醒。
> 根據這份文件教學
> https://www.tonymacx86.com/threads/guide-installing-3rd-party-kexts-el-capitan-sierra-high-sierra-mojave.268964/
> 裡面第四點
> 
> ### 4. Why should I use /Library/Extensions over Clover Injected kexts ?
> 建議kext放在/Library/Extensions，不要放在Other
> 
> 感謝你測試回報。

能否告知你的bios具体版本和必须要的bios设置呢？

**Comment by cnsilvan** [comment]
> > 因為我目前系統都跑得很正常，我也手動睡眠好幾次都可以喚醒。
> > 根據這份文件教學
> > https://www.tonymacx86.com/threads/guide-installing-3rd-party-kexts-el-capitan-sierra-high-sierra-mojave.268964/
> > 裡面第四點
> > ### 4. Why should I use /Library/Extensions over Clover Injected kexts ?
> > 建議kext放在/Library/Extensions，不要放在Other
> > 感謝你測試回報。
> 
> 又发现hdmi无法使用。hdmi链接的4K显示器

刚开机在引导页面的时候 hdmi是可用的  进入系统后就不能用了 hdmi黑屏

**Comment by xiaooloong** [comment]
> > > 因為我目前系統都跑得很正常，我也手動睡眠好幾次都可以喚醒。
> > > 根據這份文件教學
> > > https://www.tonymacx86.com/threads/guide-installing-3rd-party-kexts-el-capitan-sierra-high-sierra-mojave.268964/
> > > 裡面第四點
> > > ### 4. Why should I use /Library/Extensions over Clover Injected kexts ?
> > > 建議kext放在/Library/Extensions，不要放在Other
> > > 感謝你測試回報。
> > 
> > 
> > 又发现hdmi无法使用。hdmi链接的4K显示器
> 
> 刚开机在引导页面的时候 hdmi是可用的 进入系统后就不能用了 hdmi黑屏

我的机型也是这样，手动升级 clover 版本后 hdmi 可以使用了
https://github.com/xiaooloong/asrock_deskmini310_hackintosh
要不你试一下我的分支？我升级了 clover 版本，同时把 fakesmc 换成了 virtualsmc

**Comment by liminghuang** [comment]
hdmi目前都必須開完機後，插拔HDMI線一次才會再次正常，這是目前用核顯雙輸出都會遇到問題。

BIOS版本我停在3.4，如以下設定:
* Advanced
  * CPU Configuration
    * Intel Virtualization Technology: Disabled
  * Chipset Configuration
    * VT-d: Disabled
    * Onboard HD Audio: Enabled
  * USB Configuration
    * XHCI Hand-off: Enabled
  * Super IO Configuration
    * Serial Port: Disabled
* Security
  * Secure Boot: Disabled(by default)

**Comment by cnsilvan** [comment]
> > > > 因為我目前系統都跑得很正常，我也手動睡眠好幾次都可以喚醒。
> > > > 根據這份文件教學
> > > > https://www.tonymacx86.com/threads/guide-installing-3rd-party-kexts-el-capitan-sierra-high-sierra-mojave.268964/
> > > > 裡面第四點
> > > > ### 4. Why should I use /Library/Extensions over Clover Injected kexts ?
> > > > 建議kext放在/Library/Extensions，不要放在Other
> > > > 感謝你測試回報。
> > > 
> > > 
> > > 又发现hdmi无法使用。hdmi链接的4K显示器
> > 
> > 
> > 刚开机在引导页面的时候 hdmi是可用的 进入系统后就不能用了 hdmi黑屏
> 
> 我的机型也是这样，手动升级 clover 版本后 hdmi 可以使用了
> https://github.com/xiaooloong/asrock_deskmini310_hackintosh
> 要不你试一下我的分支？我升级了 clover 版本，同时把 fakesmc 换成了 virtualsmc

用了你的efi 挺好用的 hdmi可以使用了 而且开机不黑屏了  开机变快了 但是没有办法睡眠 睡眠唤醒后就重启了。希望持续更新

**Comment by cnsilvan** [comment]
> hdmi目前都必須開完機後，插拔HDMI線一次才會再次正常，這是目前用核顯雙輸出都會遇到問題。
> 
> BIOS版本我停在3.4，如以下設定:
> 
> * Advanced
>   
>   * CPU Configuration
>     
>     * Intel Virtualization Technology: Disabled
>   * Chipset Configuration
>     
>     * VT-d: Disabled
>     * Onboard HD Audio: Enabled
>   * USB Configuration
>     
>     * XHCI Hand-off: Enabled
>   * Super IO Configuration
>     
>     * Serial Port: Disabled
> * Security
>   
>   * Secure Boot: Disabled(by default)

之前我是3.10 按照你的版本升级为3.40  并按照设置bios后使用最新的efi文件和的clover4934版本  能够开机了 虽然可能需要开机几次才能启动 甚至拔插hdmi 但是启动后hdmi和睡眠唤醒都可以成功了 虽然不完美 但是已经很满意了

**Comment by xiaooloong** [comment]
> 用了你的efi 挺好用的 hdmi可以使用了 而且开机不黑屏了 开机变快了 但是没有办法睡眠 睡眠唤醒后就重启了。希望持续更新

我这边睡眠和唤醒是正常的。

**Comment by cnsilvan** [comment]
> > 用了你的efi 挺好用的 hdmi可以使用了 而且开机不黑屏了 开机变快了 但是没有办法睡眠 睡眠唤醒后就重启了。希望持续更新
> 
> 我这边睡眠和唤醒是正常的。
